/**
 * Generate recorded-quality audio for every listening exercise with Google Cloud Text-to-Speech
 * (Chirp 3 HD voices, one distinct voice per speaker, natural speed) and point the exercise's
 * `audioSrc` at the file.
 *
 *   node scripts/generate-audio.mjs                 # every exercise without audio
 *   node scripts/generate-audio.mjs --force         # regenerate all
 *   node scripts/generate-audio.mjs --only n5/1-supa-de-kaimono
 *
 * Auth: a Google OAuth access token with cloud-platform scope in GOOGLE_OAUTH_TOKEN, or the
 * Firebase CLI's stored refresh token (what `firebase login` saved). The Text-to-Speech API must
 * be enabled on the project. Cost is per character: the whole site is well under 100k characters.
 *
 * Output: public/audio/<level>/<slug>.mp3, mono 48 kbps, lines joined with a 650 ms pause
 * (a real JLPT recording pauses between turns). Needs ffmpeg on PATH for the join.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const web = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const PROJECT = "opusify-japanese";
const LEVELS = ["n5", "n4", "n3", "n2", "n1"];
// Alternating female/male so two-person dialogues are unmistakable; a third and fourth for group scenes.
const VOICES = ["ja-JP-Chirp3-HD-Aoede", "ja-JP-Chirp3-HD-Charon", "ja-JP-Chirp3-HD-Kore", "ja-JP-Chirp3-HD-Puck"];
const PAUSE_MS = 650;

const args = process.argv.slice(2);
const force = args.includes("--force");
const only = args[args.indexOf("--only") + 1 || -1];

async function token() {
  if (process.env.GOOGLE_OAUTH_TOKEN) return process.env.GOOGLE_OAUTH_TOKEN;
  const cfg = JSON.parse(fs.readFileSync(path.join(os.homedir(), ".config/configstore/firebase-tools.json"), "utf8"));
  const body = new URLSearchParams({
    grant_type: "refresh_token",
    refresh_token: cfg.tokens.refresh_token,
    client_id: "563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com",
    client_secret: "j9iVZfS8kkCEFUPaAeJV0sAi",
  });
  const r = await fetch("https://oauth2.googleapis.com/token", { method: "POST", body });
  const j = await r.json();
  if (!j.access_token) throw new Error("Could not get an access token from the Firebase CLI credentials; run `firebase login` or set GOOGLE_OAUTH_TOKEN.");
  return j.access_token;
}

async function synth(tok, text, voice) {
  const r = await fetch("https://texttospeech.googleapis.com/v1/text:synthesize", {
    method: "POST",
    headers: { Authorization: `Bearer ${tok}`, "Content-Type": "application/json", "x-goog-user-project": PROJECT },
    body: JSON.stringify({ input: { text }, voice: { languageCode: "ja-JP", name: voice }, audioConfig: { audioEncoding: "MP3", speakingRate: 1.0 } }),
  });
  const j = await r.json();
  if (!j.audioContent) throw new Error(`TTS ${r.status}: ${JSON.stringify(j).slice(0, 200)}`);
  return Buffer.from(j.audioContent, "base64");
}

function join(parts, out) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "nihongo-audio-"));
  const list = [];
  parts.forEach((buf, i) => {
    const p = path.join(tmp, `${i}.mp3`);
    fs.writeFileSync(p, buf);
    list.push(`file '${p.replace(/\\/g, "/")}'`);
  });
  const listFile = path.join(tmp, "list.txt");
  fs.writeFileSync(listFile, list.join("\n"));
  // Re-encode once: concat demuxer + a resampled mono 48 kbps stream; the pause is inserted per part below.
  execFileSync("ffmpeg", ["-y", "-loglevel", "error", "-f", "concat", "-safe", "0", "-i", listFile, "-ac", "1", "-ar", "24000", "-b:a", "48k", out]);
  fs.rmSync(tmp, { recursive: true, force: true });
}

function silence(ms) {
  // One cached silent clip, generated by ffmpeg.
  const p = path.join(os.tmpdir(), `nihongo-silence-${ms}.mp3`);
  if (!fs.existsSync(p)) execFileSync("ffmpeg", ["-y", "-loglevel", "error", "-f", "lavfi", "-i", "anullsrc=r=24000:cl=mono", "-t", String(ms / 1000), "-b:a", "48k", p]);
  return fs.readFileSync(p);
}

async function main() {
  const tok = await token();
  let done = 0, chars = 0;
  for (const level of LEVELS) {
    const dir = path.join(web, "content", level, "listening");
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir).filter((x) => x.endsWith(".json"))) {
      const p = path.join(dir, f);
      const e = JSON.parse(fs.readFileSync(p, "utf8"));
      const key = `${level}/${e.slug}`;
      if (only && key !== only) continue;
      const rel = `/audio/${level}/${e.slug}.mp3`;
      const out = path.join(web, "public", rel);
      if (!force && e.audioSrc === rel && fs.existsSync(out)) continue;

      const speakers = [];
      const parts = [];
      for (const [i, line] of e.script.entries()) {
        if (!speakers.includes(line.speaker)) speakers.push(line.speaker);
        const voice = VOICES[speakers.indexOf(line.speaker) % VOICES.length];
        if (i > 0) parts.push(silence(PAUSE_MS));
        parts.push(await synth(tok, line.line, voice));
        chars += line.line.length;
      }
      fs.mkdirSync(path.dirname(out), { recursive: true });
      join(parts, out);
      e.audioSrc = rel;
      fs.writeFileSync(p, JSON.stringify(e, null, 2) + "\n");
      done++;
      console.log(`${key}: ${e.script.length} lines, ${speakers.length} voices -> ${rel} (${Math.round(fs.statSync(out).size / 1024)} KB)`);
    }
  }
  console.log(`generated ${done} file(s), ${chars} characters synthesised`);
}

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
